"""Add content and deadline columns to Todo model

Revision ID: 48c4f2e9b50a
Revises: 
Create Date: 2025-02-06 04:21:49.636366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c4f2e9b50a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('limit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('limit')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
